taskkill /f /im firefox.exe
taskkill /f /im opera.exe
taskkill /f /im Maxton.exe
taskkill /f /im iexplorer.exe
taskkill /f /im WinRar.exe
taskkill /f /im Roblox.exe
taskkill /f /im ProcessHacker.exe
taskkill /f /im ProcessHacker2.exe
taskkill /f /im none.exe
taskkill /f /im ios.exe
