DEFINE BYTES 1N 0N 0N

MARKUP 		
{		
	DEFINE BYTE 10N AS NEW EXAMPLE GLOBAL CONTAINER GIT;
	GLOBAL STATIC TYPED CONTAINER cont {
		GLOBAL CONSTRUCTOR _cont_ {
			SET FOLDER FROM BYTE 10N AS (GET SELF FROM BYTE 10N) + '/TEST';
		}
		GLOBAL METHOD _compile_ *status* {
			DEFINE BYTE ON ADDRES GIT->COMPILE + 1 AS 0
			CALL GIT->COMPILE
			CALL BY ADDRES 10N TO TBLOCK TYPE
		}
		BEFORE ALL IN CONTAINER SET GLOBAL BLOCK ON ADDRES 100N {
			CONTAINER container1 {
				DELETE SELF BY SELF
			}
		}
		AFTER CONSTRUCTOR, CONTAINER CALL AND SET GLOBAL SEGMENT 'PUBLIC' {
			CALL GIT->_SET_
		}
	}	
}		
END OF MARKUP	
